awsSdkJsReference: v2.821.0

protocols:
  ec2:
    shared: ^0.3.0
  json:
    shared: ^0.3.0
    publish: true
  query:
    shared: ^0.3.0
    publish: true
  rest-json:
    shared: ^0.3.0
    publish: true
  rest-xml:
    shared: ^0.3.0
    publish: true

# Packages to generate
packages:
## ec2
  - aws_ec2_api
## rest-json protocol APIs
  - aws_accessanalyzer_api
  - aws_amplify_api
  - aws_apigateway_api
  - aws_apigatewaymanagementapi_api
  - aws_apigatewayv2_api
  - aws_appconfig_api
  - aws_appmesh_api
  - aws_appsync_api
  - aws_backup_api
  - aws_batch_api
  - aws_chime_api
  - aws_clouddirectory_api
  - aws_cloudsearchdomain_api
  - aws_codeguru_reviewer_api
  - aws_codeguruprofiler_api
  - aws_codestar_notifications_api
  - aws_cognito_sync_api
  - aws_connect_api
  - aws_connectparticipant_api
  - aws_dataexchange_api
  - aws_detective_api
  - aws_dlm_api
  - aws_ebs_api
  - aws_efs_api
  - aws_eks_api
  - aws_elastic_inference_api
  - aws_elastictranscoder_api
  - aws_es_api
  - aws_glacier_api
  - aws_greengrass_api
  - aws_groundstation_api
  - aws_guardduty_api
  - aws_imagebuilder_api
  - aws_iot_data_api
  - aws_iot_jobs_data_api
  - aws_iot1click_devices_api
  - aws_iot1click_projects_api
  - aws_iot_api
  - aws_iotanalytics_api
  - aws_iotevents_data_api
  - aws_iotevents_api
  - aws_kafka_api
  - aws_kinesis_video_archived_media_api
  - aws_kinesis_video_media_api
  - aws_kinesis_video_signaling_api
  - aws_kinesisvideo_api
  - aws_lambda_api
  - aws_lex_models_api
  - aws_lex_runtime_api
  - aws_managedblockchain_api
  - aws_marketplace_catalog_api
  - aws_mediaconnect_api
  - aws_mediaconvert_api
  - aws_medialive_api
  - aws_mediapackage_vod_api
  - aws_mediapackage_api
  - aws_mediastore_data_api
  - aws_mediatailor_api
  - aws_mobile_api
  - aws_mq_api
  - aws_networkmanager_api
  - aws_outposts_api
  - aws_personalize_events_api
  - aws_personalize_runtime_api
  - aws_pinpoint_email_api
  - aws_pinpoint_sms_voice_api
  - aws_pinpoint_api
  - aws_polly_api
  - aws_qldb_api
  - aws_quicksight_api
  - aws_ram_api
  - aws_rds_data_api
  - aws_resource_groups_api
  - aws_robomaker_api
  - aws_sagemaker_a2i_runtime_api
  - aws_sagemaker_runtime_api
  - aws_savingsplans_api
  - aws_schemas_api
  - aws_securityhub_api
  - aws_serverlessrepo_api
  - aws_sesv2_api
  - aws_signer_api
  - aws_sso_oidc_api
  - aws_sso_api
  - aws_workdocs_api
  - aws_worklink_api
  - aws_workmailmessageflow_api
  - aws_xray_api
## json protocol APIs
  - aws_acm_api
  - aws_acm_pca_api
  - aws_alexaforbusiness_api
  - aws_application_autoscaling_api
  - aws_application_insights_api
  - aws_appstream_api
  - aws_athena_api
  - aws_autoscaling_plans_api
  - aws_budgets_api
  - aws_ce_api
  - aws_cloud9_api
  - aws_cloudhsm_api
  - aws_cloudhsmv2_api
  - aws_cloudtrail_api
  - aws_codebuild_api
  - aws_codecommit_api
  - aws_codepipeline_api
  - aws_codestar_api
  - aws_codestar_connections_api
  - aws_cognito_identity_api
  - aws_cognito_idp_api
  - aws_comprehend_api
  - aws_comprehendmedical_api
  - aws_compute_optimizer_api
  - aws_configservice_api
  - aws_cur_api
  - aws_datapipeline_api
  - aws_datasync_api
  - aws_dax_api
  - aws_deploy_api
  - aws_devicefarm_api
  - aws_directconnect_api
  - aws_discovery_api
  - aws_dms_api
  - aws_ds_api
  - aws_dynamodb_api
  - aws_dynamodbstreams_api
  - aws_ec2_instance_connect_api
  - aws_ecr_api
  - aws_ecs_api
  - aws_emr_api
  - aws_events_api
  - aws_firehose_api
  - aws_fms_api
  - aws_forecast_api
  - aws_forecastquery_api
  - aws_frauddetector_api
  - aws_fsx_api
  - aws_gamelift_api
  - aws_globalaccelerator_api
  - aws_glue_api
  - aws_health_api
  - aws_inspector_api
  - aws_iotsecuretunneling_api
  - aws_iotthingsgraph_api
  - aws_kendra_api
  - aws_kinesis_api
  - aws_kinesisanalytics_api
  - aws_kinesisanalyticsv2_api
  - aws_kms_api
  - aws_lakeformation_api
  - aws_license_manager_api
  - aws_lightsail_api
  - aws_logs_api
  - aws_machinelearning_api
  - aws_macie_api
  - aws_marketplace_entitlement_api
  - aws_marketplacecommerceanalytics_api
  - aws_mediastore_api
  - aws_meteringmarketplace_api
  - aws_mgh_api
  - aws_migrationhub_config_api
  - aws_mturk_api
  - aws_opsworks_api
  - aws_opsworks_cm_api
  - aws_organizations_api
  - aws_personalize_api
  - aws_pi_api
  - aws_pricing_api
  - aws_qldb_session_api
  - aws_rekognition_api
  - aws_resourcegroupstaggingapi_api
  - aws_route53domains_api
  - aws_route53resolver_api
  - aws_sagemaker_api
  - aws_secretsmanager_api
  - aws_service_quotas_api
  - aws_servicecatalog_api
  - aws_servicediscovery_api
  - aws_shield_api
  - aws_sms_api
  - aws_snowball_api
  - aws_ssm_api
  - aws_storagegateway_api
  - aws_support_api
  - aws_swf_api
  - aws_textract_api
  - aws_transcribe_api
  - aws_transfer_api
  - aws_translate_api
  - aws_waf_api
  - aws_waf_regional_api
  - aws_wafv2_api
  - aws_workmail_api
  - aws_workspaces_api
## query protocol APIs
  - aws_autoscaling_api
  - aws_cloudformation_api
  - aws_cloudsearch_api
  - aws_cloudwatch_api
  - aws_elasticache_api
  - aws_elasticbeanstalk_api
  - aws_elb_api
  - aws_elbv2_api
  - aws_iam_api
  - aws_importexport_api
  - aws_rds_api
  - aws_redshift_api
  - aws_sdb_api
  - aws_ses_api
  - aws_sns_api
  - aws_sqs_api
  - aws_sts_api
  - aws_neptune_api
  - aws_docdb_api
## rest-xml protocol APIs
  - aws_cloudfront_api
  - aws_route53_api
  - aws_s3_api
  - aws_s3control_api
