name: aws_client
description: High-level APIs for Amazon Web Services (AWS)
version: 0.1.3
author: Istvan Soos <istvan.soos@agilord.com>

homepage: https://github.com/agilord/aws_client

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  crypto: ^2.0.1
  http_client: '>=0.5.0 <2.0.0'
  meta: ^1.0.0
  xml: ^3.0.0

dev_dependencies:
  pedantic: ^1.0.0
  test: '^1.3.0'
