name: document_client
description: |
  The DynamoDB document client simplifies working with items.
  It uses native Dart types as input parameters, as well as converts response data to native Dart types.
version: 2.0.0

homepage: https://github.com/agilord/aws_client

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  aws_dynamodb_api: ^2.0.0
  shared_aws_api: ^2.0.0

dev_dependencies:
  lints:
  test:
  http:
