name: shared_aws_api
description: Shared protocol implementation and utilities for generated AWS API clients.
version: 0.3.1

homepage: https://github.com/agilord/aws_client/tree/master/shared_aws_api

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  crypto: ^3.0.0
  http: ^0.13.0
  json_annotation: ^3.0.1
  meta: ^1.3.0
  xml: ^5.0.0
  intl: ^0.17.0
  uuid: ^3.0.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.6
  build_runner: ^1.8.0
  json_serializable: ^3.2.0
