name: shared_aws_api
description: Shared protocol implementation and utilities for generated AWS API clients.
version: 0.3.0

homepage: https://github.com/agilord/aws_client/tree/master/shared_aws_api

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  crypto: ^3.0.1
  http: ^0.13.1
  meta: ^1.3.0
  xml: ^5.0.2
  intl: ^0.17.0
  uuid: ^3.0.3
  collection: ^1.15.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
