name: shared_aws_api
description: Shared protocol implementation and utilities for generated AWS API clients.
version: 2.0.1

homepage: https://github.com/agilord/aws_client/tree/master/shared_aws_api

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  crypto: ^3.0.1
  http: '>=0.13.1 <2.0.0'
  meta: ^1.3.0
  xml:  '>=6.0.0 <7.0.0'
  intl: '>=0.18.0 <0.20.0'
  uuid: ^4.0.0
  collection: ^1.15.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.16.8
