name: aws_lambda_api
description: AWS API client for AWS Lambda
version: 0.0.1
homepage: https://github.com/agilord/aws_client/tree/master/generated/aws_lambda_api
publish_to: none

protocol: rest-json

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  shared_aws_api: 0.3.0-dev

dev_dependencies:
  build_runner: ^1.7.2
  json_serializable: ^3.2.0
  build_verify: ^1.1.1
  test: ^1.9.4


